name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-php@v4
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install --no-interaction --no-progress
      - name: Run tests
        run: vendor/bin/phpunit
